#ifndef __ewf_adapter_renesas_ryz014__h__included__
#define __ewf_adapter_renesas_ryz014__h__included__

#include "ewf_adapter_renesas_gm01q.h"

#define EWF_ADAPTER_RENESAS_RYZ014_STATIC_DECLARE EWF_ADAPTER_RENESAS_GM01Q_STATIC_DECLARE

#endif /* __ewf_adapter_renesas_ryz014__h__included__ */
