#ifndef __ewf_adapter_renesas_ryz024a__h__included__
#define __ewf_adapter_renesas_ryz024a__h__included__

#include "ewf_adapter_renesas_gm02s.h"

#define EWF_ADAPTER_RENESAS_RYZ024A_STATIC_DECLARE EWF_ADAPTER_RENESAS_GM02S_STATIC_DECLARE

#endif /* __ewf_adapter_renesas_ryz024a__h__included__ */
